---
# use my own docker:stable image that has
# ansible and molecule added
image: qwe1/dind-ansible-molecule:latest

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # https://gitlab.com/gitlab-org/gitlab-ce/issues/64959
  # 19.03 had some breaking changes compared to 18.09
  DOCKER_TLS_CERTDIR: ""
  ROLE_NAME: ansible-role-openvpn_server
  GALAXY_USERNAME: richardskumat
  GALAXY_ROLENAME: ansible_role_openvpn_server


services:
  - docker:dind

stages:
  - test

before_script:
  - docker info
  - ansible --version
  - molecule --version
  - cd ..
  - cp -aR $ROLE_NAME $GALAXY_USERNAME.$GALAXY_ROLENAME
  - cd $GALAXY_USERNAME.$GALAXY_ROLENAME

test_d9:
  stage: test
  variables:
    MOLECULE_DISTRO: "debian:9"
  script:
    - molecule test

# d10 comes with easyrsa 3.0.6 which I don't have any tasks for in this role
#test_d10:
#  stage: test
#  variables:
#    MOLECULE_DISTRO: "debian:10"
#  script:
#    - molecule test
