---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: easyrsa.yml

- include_tasks: serverconf.yml

- include_tasks: clientcommon.yml

- include_tasks: createovpn.yml

- include_tasks: sysctl.yml

- include_tasks: iptables.yml

- include_tasks: fetchovpn.yml

